eclipse/january

- org.eclipse.january.form.test/META-INF/MANIFEST.MF
- org.eclipse.january.form.test/src/org/eclipse/ice/datastructures/entry/test/FileEntryTester.java
- org.eclipse.january.form.test/src/org/eclipse/ice/datastructures/test/GeometryComponentTester.java
- org.eclipse.january.form.test/src/org/eclipse/ice/datastructures/test/ResourceHandlerTester.java
- org.eclipse.january.form/META-INF/MANIFEST.MF
- org.eclipse.january.form/OSGI-INF/VizServiceFactoryHolder.xml
- org.eclipse.january.form/src/org/eclipse/january/form/GeometryComponent.java
- org.eclipse.january.form/src/org/eclipse/january/form/ResourceHandler.java
- org.eclipse.january.form/src/org/eclipse/january/form/internal/VizServiceFactoryHolder.java
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.target
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.tpd
> Update ICE's January contribution 

- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyMathsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyMaths.java
Also: original sum method is now invoking Dataset.sum when dealing with
an instance of Dataset...
Signed-off-by: Tom Schoonjans <Tom.Schoonjans@diamond.ac.uk>
> LazyMaths: overload sum method with multiple axes

- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january.test/pom.xml
- org.eclipse.january/META-INF/MANIFEST.MF
- org.eclipse.january/pom.xml
Update version number as interfaces have changed
> Update version number to 1.1.0

- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/Dataset.java
Amend getter names, alter semantics for compound datasets, and refactor complex datasets
> Add part methods

- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january/META-INF/MANIFEST.MF
Will update the version numbers globally later...
> Revert manifest version number too to fix build

- org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/IterationExamples.java
- org.eclipse.january.examples/src/org/eclipse/january/tutorial/C1TheBasics.java
As an alternative to issue #24, show how to use classes for factory method arguments in place of Dataset constants
> Update examples to use classes instead of constants

- .travis.yml
https://github.com/eclipse/january/issues/68
> Attempt to add build and test using travis to repository.

- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
For #27, this is the proposed PR.
> Synchronize some metadata methods to make them threadsafe

- org.eclipse.january/src/org/eclipse/january/metadata/internal/StatisticsMetadataImpl.java
Also refactor to remove use of transients
> Fix copy constructor

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/StatsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractCompoundDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/Dataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/Stats.java
- org.eclipse.january/src/org/eclipse/january/metadata/Dirtiable.java
- org.eclipse.january/src/org/eclipse/january/metadata/StatisticsMetadata.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/ErrorMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/StatisticsMetadataImpl.java
Also fix reshaped metadata bug caused by not cloning metadata and extend unit tests
> Add annotation to ensure stats are flagged as stale

- org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/SlicingExamples.java
Not sure which is best way to slice but this example works reliably.
> Added example for nD slicing. There are a lot of ways of doing this.

- org.eclipse.january/META-INF/MANIFEST.MF
> Add version info to exported packages.

- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/Dataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/IDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/Stats.java
- org.eclipse.january/src/org/eclipse/january/metadata/Dirtiable.java
> Add missing @since 2.0 tags

- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
> Update Example to point at 2.0RC1

- CONTRIBUTING.md
> Update contributing guide to point to emerging info on Wiki

- .travis.yml
> Bug #109: Improve build script on travis

- org.eclipse.january.test/src/org/eclipse/january/dataset/StatsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/Stats.java
Add unit tests for quantile, iqr, skewness and kurtosis
> Fix bug #112 where NPEs were thrown and also some other bugs

- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
> Update Example to point at 2.0.0 Release

- org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/AxesMetadataExample.java
**Initially for discussion, Not ready for merge**
In this PR I'm developing an new example class that demonstrates how to use interpolation to exploit values in AxesMetadata.  Though measurements may have been taken at different times (or elevations in this balloon ascent example), interpolation can be used to synchronise the values, as discussed in issue #116 
Signed-off-by: Ian Mayo <ian@planetmayo.com>
> New January example, to investigate interpolating non-synced datasets

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/StatsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/Stats.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/StatisticsMetadataImpl.java
Fixes from master for a bug fix release
> January 2.0 fixes

- org.eclipse.january/pom.xml
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.tpd
> #125 Generate javadocs during build

- org.eclipse.january.asserts/META-INF/MANIFEST.MF
- org.eclipse.january.asserts/pom.xml
- org.eclipse.january.examples/META-INF/MANIFEST.MF
- org.eclipse.january.examples/pom.xml
- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january.test/pom.xml
- org.eclipse.january/META-INF/MANIFEST.MF
- org.eclipse.january/pom.xml
- pom.xml
- releng/org.eclipse.january.releng.p2/category.xml
- releng/org.eclipse.january.releng.p2/pom.xml
- releng/org.eclipse.january.releng.target/january-baseline.target
- releng/org.eclipse.january.releng.target/january-baseline.tpd
- releng/org.eclipse.january.releng.target/pom.xml
- releng/org.eclipse.january.releng/pom.xml
> Update master branch to 2.1.0-SNAPSHOT

- org.eclipse.january.asserts/META-INF/MANIFEST.MF
- org.eclipse.january.asserts/pom.xml
- org.eclipse.january.examples/META-INF/MANIFEST.MF
- org.eclipse.january.examples/pom.xml
- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january.test/pom.xml
- org.eclipse.january/META-INF/MANIFEST.MF
- org.eclipse.january/pom.xml
- pom.xml
- releng/org.eclipse.january.releng.p2/category.xml
- releng/org.eclipse.january.releng.p2/pom.xml
- releng/org.eclipse.january.releng.target/january-baseline.target
- releng/org.eclipse.january.releng.target/january-baseline.tpd
- releng/org.eclipse.january.releng.target/pom.xml
- releng/org.eclipse.january.releng/pom.xml
> Update january_2_0 branch to 2.0.1-SNAPSHOT

- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
> Update examples for 2.0.1 release

- org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/AxesMetadataExample.java
> spelling mistake

- org.eclipse.january.examples/pom.xml
- org.eclipse.january.examples/src/org/eclipse/january/test/AllExamplesTestSuite.java
- releng/org.eclipse.january.releng/pom.xml
> #126: Test examples as part of the build

- org.eclipse.january/src/org/eclipse/january/dataset/InterpolatorUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/LinearAlgebra.java
Deleted 4 unused private methods.
> removed unused private methods

- README.md
Fixes #147 
(also removed stray new-line at end of file)
Signed-off-by: Ian Mayo <ian@planetmayo.com>
> Switch to correct URL

- README.md
> #125: Update location of javadocs

- org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/SlicingExamples.java
- org.eclipse.january/src/org/eclipse/january/dataset/Slice.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceND.java
Signed-off-by: Pierre Sachot <sachot.pierre@laposte.net>
> Added Slice documentation and new Slices examples.

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetUtilsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
Split method testing if ">" but should test if ">=".
Added a test for this exception.
> Bugfix: Exception in split method not working as intented

- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
Removed a useless assignment in the conditional operator
> Remove useless assignment

- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
I removed the reset part for Dataset.INT8,INT16,INT32,INT64,FLOAT32 and
FLOAT64 because the reset can't be true, DTypeUtils.getElementsPerItem()
always return 1 for thoses types.
Signed-off-by: Pierre Sachot <sachot.pierre@laposte.net>
> Maths.java unused code

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetUtilsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
This allows through datasets which are non-negative
> Add check option to make unsigned method

- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/GeneratedMaths.java
- org.eclipse.january/src/org/eclipse/january/dataset/SingleInputBroadcastIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
Part fix for #187, expand broadcasting to allow output to have a single element per item, and tests
> Fix compound dataset handling in Maths methods

- org.eclipse.january/src/org/eclipse/january/metadata/AxesMetadata.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/AxesMetadataImpl.java
Use an identity hash map directly instead of manually and improve javadocs
> Refactor axes metadata

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/IntegersIterator.java
Also replace deprecated factory callers
> Allow negative indexes in accessors that use integer datasets

- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/Dataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Defer dirtyMetadata call until metadata is fetched
> Speed up set dirty as it is called in all dataset item setters (#197)

- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsArrayTypeAbsFunctionParameterizeTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsBasicTypeAbsFunctionParameterizeTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsComplexAbsFunctionParameterizeTest.java
Adding ParameterizeTest on Maths.abs for Complex and Arrays.
Signed-off-by: Pierre Sachot <sachot.pierre@laposte.net>
> JUnit Test: ParameterizeTest Maths.java

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetUtilsTest.java
> Added tests for some methods in DatasetUtils

- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/IntegerDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/ByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/FloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/IntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ObjectDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/ShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/StringDatasetBase.java
When a slice view of size one of a dataset is given to these methods, the wrong value can be retrieved
> Fix in-place methods for corner case

- org.eclipse.january.test/src/org/eclipse/january/dataset/SingleInputBroadcastIteratorTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/SingleInputBroadcastIterator.java
Failures occurred when there were negative strides
> Fix broadcasting of a single dataset to an optional output dataset

- org.eclipse.january/src/org/eclipse/january/dataset/SingleInputBroadcastIterator.java
Value is used only in the zero-rank case
> Remove unnecessary calculation

- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastPairIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastSingleIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/ContiguousIteratorWithPosition.java
- org.eclipse.january/src/org/eclipse/january/dataset/DiscontiguousIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/IntegerIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/PositionIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/SingleInputBroadcastIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceIterator.java
Remove unnecessary calculations and assignments
> Clean up iterators

- org.eclipse.january.test/src/org/eclipse/january/dataset/BooleanIteratorTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanBroadcastIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanContiguousIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanIteratorBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanNullIterator.java
Add specialized iterators to add broadcasting and add more tests
> Refactor boolean iterators

- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyMathsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyMaths.java
as well as some other minor changes...
> Lazymaths: add min, max and median methods

- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyMathsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyMaths.java
* Removes `median` method
* Improves performance of `max()` and `min()` methods dramatically
> Lazymaths maxmin fixes

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/ByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/FloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/IntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/LongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ObjectDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/ShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/StringDatasetBase.java
Also set clean if metadata is null
> Fix wrong dirty state when filling other dataset

- org.eclipse.january.test/src/org/eclipse/january/dataset/AllSuite.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/BooleanDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ParameterizeDatasetTests.java
> Dataset coverage

- GRADLE.md
Signed-off-by: Matthew Gerring <matthew.gerring@gmail.com>
> Added gradle.md to explain use with gradle.

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AxesMetadataTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
But also do not override it when it has been cleared
> Copy original metadata on slice

- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
> [releng] Update examples to point at 2.1.4RC1

- org.eclipse.january.asserts/META-INF/MANIFEST.MF
- org.eclipse.january.asserts/pom.xml
- org.eclipse.january.examples/META-INF/MANIFEST.MF
- org.eclipse.january.examples/pom.xml
- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january.test/pom.xml
- org.eclipse.january/META-INF/MANIFEST.MF
- org.eclipse.january/pom.xml
- pom.xml
- releng/org.eclipse.january.releng.p2/category.xml
- releng/org.eclipse.january.releng.p2/pom.xml
- releng/org.eclipse.january.releng.target/pom.xml
- releng/org.eclipse.january.releng/pom.xml
> [releng] Set version to 2.1.4

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AllSuite.java
- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/MetadataFactoryTest.java
- org.eclipse.january/src/org/eclipse/january/metadata/ErrorMetadata.java
- org.eclipse.january/src/org/eclipse/january/metadata/MetadataFactory.java
- org.eclipse.january/src/org/eclipse/january/metadata/UnitMetadata.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/ErrorMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/UnitMetadataImpl.java
Also, add second initialize method to error metadata to allow testing, add metadata factory creation and serialization tests
> Fix #323 add missing initialize method to unit metadata (#324)

- org.eclipse.january/META-INF/MANIFEST.MF
Closes #278
Signed-off-by: Tom Schoonjans <Tom.Schoonjans@diamond.ac.uk>
> MANIFEST: reexport javax.measure.unit-api (#279)

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractCompoundDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
Cherry pick #334 from 2.1 branch
> Fix #332 by copying data when the view is not contiguous

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractCompoundDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDynamicDataset.java
- org.eclipse.january/src/org/eclipse/january/metadata/StatisticsMetadata.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/StatisticsMetadataImpl.java
Handle unmarshalling bugs which caused by reference to containing dataset, when state is dirty, ensure metadata is cleared
> Fix bugs in statistics metadata

- org.eclipse.january/.settings/.api_filters
- releng/org.eclipse.january.releng.target/january-baseline.target
> Update API baseline to 2.1

- .travis.yml
- GRADLE.md
- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
- org.eclipse.january/pom.xml
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.target
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.tpd
- releng/org.eclipse.january.releng/pom.xml
Make dependencies consistent too
> Update target platform to Photon

- .travis.yml
- GRADLE.md
- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
- org.eclipse.january/pom.xml
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.target
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.tpd
Make dependencies consistent too
> Update target platform to Photon (#344)

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AxesMetadataTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Add missing handling for size-1 lazy datasets and remove checks for zero rank in metadata reshaping
> Fix scalar metadata reshaping

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AxesMetadataTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Add missing handling for size-1 lazy datasets and remove checks for zero rank in metadata reshaping
> Fix scalar metadata reshaping (#350)

- org.eclipse.january.test/src/org/eclipse/january/dataset/BroadcastIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/BroadcastSelfIteratorTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastPairIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastSingleIterator.java
> Broadcasting a scalar view causes an array index exception

- org.eclipse.january/src/org/eclipse/january/dataset/ContiguousIteratorWithPosition.java
> Fix for compound datasets (not used(!))

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetUtilsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DTypeUtils.java
> Fix bug when cast to a complex dataset (#360)

- org.eclipse.january/src/org/eclipse/january/metadata/internal/AxesMetadataImpl.java
> Override toString to aid debugging axes metadata problems (#361)

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetFactoryTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetFactory.java
> Allow datasets to be list for createFromList (#362)

- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
> [releng] Update examples to point at 2.2.1RC2

- org.eclipse.january.asserts/META-INF/MANIFEST.MF
- org.eclipse.january.asserts/pom.xml
- org.eclipse.january.examples/META-INF/MANIFEST.MF
- org.eclipse.january.examples/pom.xml
- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january.test/pom.xml
- org.eclipse.january/META-INF/MANIFEST.MF
- org.eclipse.january/pom.xml
- pom.xml
- releng/org.eclipse.january.releng.p2/category.xml
- releng/org.eclipse.january.releng.p2/pom.xml
- releng/org.eclipse.january.releng.target/pom.xml
- releng/org.eclipse.january.releng/pom.xml
> [releng] Set version to 2.2.1

- org.eclipse.january.examples/JanuaryExamples.target
- org.eclipse.january.examples/JanuaryExamples.tpd
> [releng] Update examples to point at 2.2.1

- GRADLE.md
- org.eclipse.january.asserts/META-INF/MANIFEST.MF
- org.eclipse.january.asserts/pom.xml
- org.eclipse.january.examples/META-INF/MANIFEST.MF
- org.eclipse.january.examples/pom.xml
- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january.test/pom.xml
- org.eclipse.january/META-INF/MANIFEST.MF
- org.eclipse.january/pom.xml
- pom.xml
- releng/org.eclipse.january.releng.p2/category.xml
- releng/org.eclipse.january.releng.p2/pom.xml
- releng/org.eclipse.january.releng.target/pom.xml
- releng/org.eclipse.january.releng/pom.xml
> [releng] Set version to 2.2.2-SNAPSHOT

- org.eclipse.january.test/src/org/eclipse/january/dataset/BooleanDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ByteDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComparisonsTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComplexDoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComplexFloatDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/CompoundDoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetFactoryTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DateDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/FloatDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/IntegerDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LongDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ObjectDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/RGBDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ShortDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/StringDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetFactory.java
- org.eclipse.january/src/org/eclipse/january/dataset/ObjectDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/StringDataset.java
Add unit tests for creating zero rank datasets for most types
> Allow zero rank boolean and compound datasets to be created

- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDynamicDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
Use clone constructors so subclasses need not clone common fields
> Refactor lazy dataset cloning

- org.eclipse.january.test/src/org/eclipse/january/dataset/BooleanDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ByteDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComparisonsTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComplexDoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComplexFloatDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/CompoundDoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetFactoryTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DateDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/FloatDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/IntegerDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LongDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ObjectDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/RGBDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ShortDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/StringDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DTypeUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetFactory.java
- org.eclipse.january/src/org/eclipse/january/dataset/ObjectDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/StringDataset.java
Add unit tests for creating zero rank datasets for most types
> Allow zero rank boolean, object and compound datasets to be created

- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
Ensure imaginary parts are set properly and integer only operands are handled correctly too
> Fix handling of complex output case in mathematical functions

- org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/NumpyExamples.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LinearAlgebraTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/RGBDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/AggregateDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/Dataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/IntegerIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/LinearAlgebra.java
- org.eclipse.january/src/org/eclipse/january/dataset/RunningAverage.java
- org.eclipse.january/src/org/eclipse/january/dataset/Stats.java
Add new class-based methods to replace deprecated Dataset constant usage, update existing callers
> More Dataset constants update

- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyWriteableDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsTest.java
- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/SliceableMetadataTest.java
- org.eclipse.january/.settings/.api_filters
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/AggregateDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanNullIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DTypeUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetFactory.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/InterfaceUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDynamicDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LinearAlgebra.java
- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
- org.eclipse.january/src/org/eclipse/january/dataset/ShapeUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/SingleInputBroadcastIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/Stats.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/MathsPreface.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
- org.eclipse.january/src/org/eclipse/january/metadata/internal/StatisticsMetadataImpl.java
Add new InterfactUtils, add and move some methods to it and update existing callers of DTypeUtils
> More dataset type migration

- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/functions.txt
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
> Add single-sided clip functions

- org.eclipse.january/.settings/.api_filters
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
> Update since tag and API filters

- org.eclipse.january/src/org/eclipse/january/dataset/DatasetFactory.java
Could support it and BigDecimal properly in the future
> Remove one-off special case of handling BigInteger

- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/functions.txt
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
Remove trivial identity checks and dead code by add special case handling of real denominators
> Clean up Maths.java

- org.eclipse.january.test/src/org/eclipse/january/dataset/SliceNDIteratorTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceNDIterator.java
When no axes are omitted for SliceNDIterator, the destination slice has the wrong shape
> Fix bug in shape of destination slice for iterator

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyDynamicLoaderTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/SliceNDTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractCompoundDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceND.java
Fix where new checks fail, add method to update its source shape and add new unit tests
> Add checks on input SliceND

- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Property is no longer in use so remove code and also remove now superfluous argument
> Remove exception catching switch

- org.eclipse.january.test/src/org/eclipse/january/dataset/MathsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/MathsPreface.java
This can cause wrong results and also throw ArrayIndexOutOfBoundsExceptions
> Fix derivative on slice views issue

- .github/workflows/ci.yaml
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromcpddouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromcpxdouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromdouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generate_all.sh
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/markers.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/verify_all.sh
Remove need to install Python 2 in workflow
> Make generator scripts run with Python 3

- .github/workflows/ci.yaml
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromcpddouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromcpxdouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromdouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generate_all.sh
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/markers.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/verify_all.sh
Remove need to install Python 2 in workflow
> Make generator scripts run with Python 3 (#442)

- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromcpddouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromcpxdouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/fromdouble.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generate_all.sh
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/generatefunctions.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/markers.py
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/verify_all.sh
Regenerate Maths class because dictionary key order differs
> Switch over to Python 3

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetFactoryTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/RGBByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/RGBDataset.java
Correct values check, remove shallow copy from copy method, add more tests
> Add new compound constructor for RGB datasets

- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyWriteableDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
Also convert test method calls to static imports
> Fix NPE from null slice

- org.eclipse.january/.settings/.api_filters
- org.eclipse.january/src/org/eclipse/january/dataset/IDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ILazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ILazyWriteableDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
> Override squeeze end method in sub-interface

- org.eclipse.january.test/META-INF/MANIFEST.MF
- org.eclipse.january/.settings/.api_filters
- org.eclipse.january/src/org/eclipse/january/dataset/IDynamicDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ILazyWriteableDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDynamicDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
Update test plugin fragment host version
> Move chunking accessors up from lazy writeable dataset to dynamic dataset

- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Merge all changes from 2.3 branch
> Fix type erasure ambiguities for Java 8

- org.eclipse.january.test/src/org/eclipse/january/dataset/BooleanDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ByteDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComplexDoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComplexFloatDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/CompoundDoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DateDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/FloatDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/IntegerDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LongDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ObjectDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/RGBByteDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/RGBDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ShortDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/StringDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/InterfaceUtils.java
Some datasets sub-classes were not found from internal maps. Add to unit tests
> Fix bugs in interface utilities

- org.eclipse.january.test/src/org/eclipse/january/dataset/RGBByteDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/RGBByteDataset.java
> Override element getters to return unsigned numbers

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/SliceNDTest.java
- org.eclipse.january/.settings/.api_filters
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractCompoundDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDynamicDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceND.java
Fix isAll for slice of zero-sized (so returns false), NPE in toString for null slice. Add unit tests.
> Refactor slice shape checking and allow for maximum shape
