- org.eclipse.january.geometry.xtext.iges/META-INF/MANIFEST.MF
- org.eclipse.january.geometry.xtext.iges/build.properties
- org.eclipse.january.geometry/META-INF/MANIFEST.MF
- org.eclipse.january.geometry/build.properties
- org.eclipse.january.geometry/plugin.properties
Removed additional.bundles statements from the build.properties,
replacing them with imports in the manifest files. 
This addresses issue #2 
Signed-off-by: Robert Smith <smithrw@ornl.gov>
> Removed additional.bundles statements

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractCompoundDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/BroadcastIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyDynamicLoaderTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
Position arrays must have lengths that match dataset rank and rank-specific accessors succeed only when called on matching datasets
> Tighten position accessor requirements

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastSingleIterator.java
The broadcast iterator must not broadcast to the destination dataset; only the source dataset should be broadcast
> Fix setting slice with an incompatible shape

- org.eclipse.january.test/src/org/eclipse/january/dataset/ComparisonsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/Comparisons.java
Changes nonZero method in Comparisons to return a list of empty datasets
(rank 1, size 0) for each dimension if no non-zero values are present.
This is to be consistent with the usual behaviour (and numpy).
Signed-off-by: Charles Mita <charles.mita@diamond.ac.uk>
> nonZero to return empty dataset if no non-zero value in dimension

- org.eclipse.january/src/org/eclipse/january/dataset/DatasetFactory.java
*Note: Demonstration PR, not ready for merge*
I think it would be respectful to future adopters to mark the create() methods that were used in the earlier tutorials as deprecated - to gently push them towards the class based dataset generators.  This was briefly discussed here: https://github.com/eclipse/january/issues/24#issuecomment-280679340
If this comment description is valid, then I'm happy to spend a few minutes adding javadoc markers & annotations to the other methods that use the legacy `dtype` data type parameter.  Then I'll update the PR.
Signed-off-by: Ian Mayo <ian@planetmayo.com>
> Suggested javadoc to mark deprecation of legacy methods

- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.target
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.tpd
Until now all new style Oribit bundles were never released in an R
build. Even though this is called a Neon build it contains
the correct versions of the bundles we require for January.
> Update target platform to use R build of Orbit

- org.eclipse.january.test/src/org/eclipse/january/dataset/AllSuite.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/UnsignedArithmeticsTest.java
There was an UnsignedArithmetics in both the test bundle and the
main bundle with the same name. Until now that caused no problem
that anyone noticed, but today PDE decided to complain.
> Rename UnsignedArithmetics to ...Test

- org.eclipse.january/.pydevproject
Switch to a Jython interpreter called Jython2 and include the class file directory to enable runners launched from the IDE to find built classes
> Correct PyDev configuration

- org.eclipse.january/pom.xml
- releng/org.eclipse.january.releng.target/org.eclipse.january.releng.target.tpd
This PR adds generating javadocs as part of the build. 
As there are some errors in the javadoc we specify  `<failOnError>false</failOnError>` A separate issue will be raised to track these issues.
> #125 Generate javadocs during build

- README.md
This is a squashed cherry-pick of:
645c98b056cf0b99514ada07c6646559584f3768: Switch to correct URL (#148)
cca12551136d9854583f791c097c7f03ad75e548: #125: Update location of javadocs (#149)
Signed-off-by: Ian Mayo <ian@planetmayo.com>
Also-by: Ian Mayo <ian@planetmayo.com>
> Fix URLs in README.

- org.eclipse.january/pom.xml
The exec-maven-plugin is executing a .sh file, which windows can't do.
I created a profile activated by being on a unix based platform that runs this plugin.
> profile for unix command

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetUtilsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
It now checks if the number of values on the yAxis is at least equal to the
number of values on the xAxis. If this is not the case, it raises a
IllegalArgumentException.
> Added an exception case to crossings in DatasetUtils

- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
This is because it violates common pattern for getElement*Abs and can cause ArrayIndexOutOfBound exceptions
> Remove aggregation of boolean elements

- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/Dataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Defer dirtyMetadata call until metadata is fetched
> Speed up set dirty as it is called in all dataset item setters

- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetUtilsTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
crossings(Dataset xAxis, Dataset yAxis, double yValue, double xRangeProportion)
not working properly.
If there are exactly 3 crossings that could have been merged it is not done
because it was using "<" instead of "<=".
> Fix crossings not working properly in DatasetUtils

- .travis.yml
Travis-CI has updated their Ubuntu Trusty 14.04 images and it looks like it no longer has oraclejdk7
> Switch to using OpenJDK 7 to build

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/SliceableMetadataTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Includes simple test that fails without the fix
> Fix bug in slicing metadata with broadcasting and a step > 1

- org.eclipse.january/META-INF/MANIFEST.MF
Re-exporting unit-api causes namespace clashes in existing code that use JScience.
This reverts commit 8cec54b7aa708b6c0d21acfe15d8f401d3ca8cc1.
> Revert "MANIFEST: reexport javax.measure.unit-api (#279)"

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AxesMetadataTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Metadata slicing (and other processing) works on datasets in place thus we need to ensure we do not overwrite the original metadata that is restored on slicing
> Fix #302 by making a deeper copy of the original metadata on restore

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AxesMetadataTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
Negative start/end points are re-interpreted when the 3-integer array getter is used
> Fix 306 by using an ND slice

- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AllSuite.java
- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/MetadataFactoryTest.java
- org.eclipse.january/src/org/eclipse/january/metadata/ErrorMetadata.java
- org.eclipse.january/src/org/eclipse/january/metadata/MetadataFactory.java
- org.eclipse.january/src/org/eclipse/january/metadata/UnitMetadata.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/ErrorMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/UnitMetadataImpl.java
Also, add second initialize method to error metadata to allow testing, add metadata factory creation and serialization tests
> Fix #323 add missing initialize method to unit metadata

- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyWriteableDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ShapeUtilsTest.java
- org.eclipse.january.test/src/org/eclipse/january/metadata/internal/AxesMetadataTest.java
- org.eclipse.january/.settings/.api_filters
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDynamicDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyWriteableDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ShapeUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/Slice.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceND.java
Clarify in code that internal operations always happens to given order, allow intermediate unit dimensions to be added, extend tests to all combinations of operations
> Fix lazy dataset slicing, transposing and shaping bugs

- org.eclipse.january.test/src/org/eclipse/january/dataset/RGBDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/RGBDataset.java
The issue occurs when a non-contiguous dataset is passed as an argument.
> Fix three dataset constructor bug

- org.eclipse.january.test/src/org/eclipse/january/dataset/CompoundDoubleDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DoubleDatasetTest.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/StatisticsMetadataImpl.java
When a zero-sized dataset is created then calling maxPos/minPos throws an index out of bounds exception. It is less puzzling for callers to throw an unsupported operation exception for max/min and maxPos/minPos in this case.
> Fix zero-sized dataset statistics

- org.eclipse.january/src/org/eclipse/january/dataset/Maths.java
- org.eclipse.january/src/org/eclipse/january/dataset/internal/template/functions.txt
When a complex divisor is used and its imaginary part has greater magnitude than its real part, the imaginary part of the result was wrong
> Correct imaginary parts of a complex division

- org.eclipse.january.test/src/org/eclipse/january/dataset/BroadcastIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/BroadcastUtilsTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/ComparisonsTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/DatasetFactoryTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/IndexIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/IntegersIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/PositionIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/SliceIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/SliceNDIteratorTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/StrideIteratorTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/BroadcastUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/ContiguousIteratorWithPosition.java
- org.eclipse.january/src/org/eclipse/january/dataset/IntegersIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/NullIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/PositionIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/Slice.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceND.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceNDIterator.java
- org.eclipse.january/src/org/eclipse/january/dataset/StrideIterator.java
Zero-sized datasets return null for a shape reference but this can cause NPEs for SliceND and dataset iterators
> Fix null shape bugs

- org.eclipse.january/src/org/eclipse/january/dataset/ILazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
The dataset interface may not be known or too costly to work out when the lazy dataset is constructed
> Allow lazy datasets to have an undefined dataset interface

- org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/Utils.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractCompoundDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/AbstractDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/BooleanDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/ByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ComplexFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundByteDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundDoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundFloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundIntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundLongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/CompoundShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/DTypeUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/DatasetUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/DateDatasetImpl.java
- org.eclipse.january/src/org/eclipse/january/dataset/DoubleDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/FloatDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/IntegerDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyMaths.java
- org.eclipse.january/src/org/eclipse/january/dataset/LongDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ObjectDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/RGBDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/ShortDataset.java
- org.eclipse.january/src/org/eclipse/january/dataset/StringDatasetBase.java
Replace use of inherited loggers with class specific logger fields.
Fixes #428
> Convert to use class specific loggers (#428)

- pom.xml
- releng/org.eclipse.january.releng/pom.xml
Caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=565644#c12 so update version of jarsigner to use new infrastructure. Also remove unnecessary prerequisites
> Fix jenkins build

- pom.xml
- releng/org.eclipse.january.releng/pom.xml
Caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=565644#c12 so update version of jarsigner to use new infrastructure. Also remove unnecessary prerequisites
> Fix jenkins build for master

- org.eclipse.january.test/src/org/eclipse/january/dataset/LazyDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/SliceNDTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/LazyDatasetBase.java
- org.eclipse.january/src/org/eclipse/january/dataset/ShapeUtils.java
- org.eclipse.january/src/org/eclipse/january/dataset/SliceND.java
Add axes metadata to test, convert test method calls to static imports
> Fix slicing of metadata in lazy datasets
